apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: actual-budget
commonLabels:
  app.kubernetes.io/part-of: actual-budget

resources:
  - manifests/namespace.yml
  - manifests/deployment.yml
  - manifests/service.yml
  - manifests/pvc.yml
  - manifests/ingress.yml

images:
  - name: ghcr.io/actualbudget/actual-server
    newTag: "24.12.0"

configMapGenerator:
  - name: actual-config
    envs:
      - config.env
