# change service type to node-port
- op: replace
  path: /spec/type
  value: NodePort

# define node-port statically so that haproxy knows where to connect to
- op: add
  path: /spec/ports/0/nodePort
  value: 30080
- op: add
  path: /spec/ports/1/nodePort
  value: 30443
