apiVersion: v1
kind: List
items:

  # service (intern only)
  - apiVersion: v1
    kind: Service
    metadata:
      name: pixeldike-intern
      labels: &labels
        app.kubernetes.io/name: pixeldike
        app.kubernetes.io/component: pixelflut-server
    spec:
      selector: *labels
      ports:
        - name: pixelflut-udp
          port: 1234
          protocol: UDP
          targetPort: pixelflut-udp
        - name: pixelflut-tcp
          port: 1234
          protocol: TCP
          targetPort: pixelflut-tcp
        - name: pixelflut-ws
          port: 1235
          targetPort: pixelflut-ws

  # service for external connections
  - apiVersion: v1
    kind: Service
    metadata:
      name: pixeldike-extern
      labels: *labels
    spec:
      selector: *labels
      type: NodePort
      ports:
        - name: pixelflut-udp
          port: 30000
          nodePort: 30000
          protocol: UDP
          targetPort: pixelflut-udp
        - name: pixelflut-tcp
          port: 30000
          nodePort: 30000
          protocol: TCP
          targetPort: pixelflut-tcp

  # deployment
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: pixeldike
      labels: *labels
    spec:
      selector:
        matchLabels: *labels
      replicas: 1
      strategy:
        type: Recreate
      template:
        metadata:
          labels: *labels
        spec:
          volumes:
            - name: pixmap
              persistentVolumeClaim:
                claimName: pixmap
          containers:
            - name: pixeldike
              image: ghcr.io/lilioid/pixeldike
              args:
                - --verbose
                - server
                - --listen=tcp://0.0.0.0:1234
                - --listen=udp://0.0.0.0:1234
                - --listen=ws://0.0.0.0:1235
                - --load-snapshot=/srv/data/homepage.pixmap
                - --snapshot=/srv/data/homepage.pixmap
                - --rtmp-stream=rtmp://mediamtx:1935/stream/pixelflut
              ports:
                - name: pixelflut-tcp
                  containerPort: 1234
                  protocol: TCP
                - name: pixelflut-udp
                  containerPort: 1234
                  protocol: UDP
                - name: pixelflut-ws
                  containerPort: 1235
                  protocol: TCP
              volumeMounts:
                - name: pixmap
                  mountPath: /srv/data/

  # storage
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: pixmap
      labels: *labels
    spec:
      storageClassName: local-path
      accessModes: [ ReadWriteOnce ]
      resources:
        requests:
          storage: 500M
