# replace the existing gpg-keys volume definition to include secret gpg keys as well
- op: replace
  path: /spec/template/spec/volumes/2
  value:
    name: gpg-keys
    projected:
      sources:
        - secret:
            name: argocd-gpg-keys
        - configMap:
            name: argocd-gpg-keys-cm


# set environment variables so that gpg work correctly
- op: add
  path: /spec/template/spec/containers/0/env/-
  value:
    name: GNUPGHOME
    value: /app/config/gpg/keys
