apiVersion: v1
kind: List
items:

  - apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: woodpecker-agent
      labels: &labels
        app.kubernetes.io/name: woodpecker-agent
        app.kubernetes.io/component: ci-runner

  - apiVersion: rbac.authorization.k8s.io/v1
    kind: Role
    metadata:
      name: woodpecker-agent
      labels: *labels
    rules:
      - apiGroups: [ "" ] # "" indicates core apiGroup (don't remove)
        resources: ["persistentvolumeclaims", "services", "secrets"]
        verbs: ["create", "delete"]
      - apiGroups: [""]
        resources: [ "pods" ]
        verbs: ["watch", "create", "delete", "get", "list"]
      - apiGroups: [""]
        resources: [ "pods/log" ]
        verbs: ["get"]

  - apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      name: woodpecker-agent
      labels: *labels
    subjects:
      - kind: ServiceAccount
        name: woodpecker-agent
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: Role
      name: woodpecker-agent

  -
