apiVersion: v1
kind: List
items:

  - apiVersion: v1
    kind: Service
    metadata:
      name: woodpecker-server
      labels: &labels
        app.kubernetes.io/name: woodpecker-server
        app.kubernetes.io/component: ci-coordinator
    spec:
      selector: *labels
      ports:
        - name: http
          port: 8000
          targetPort: http
        - name: grpc
          port: 9000
          targetPort: grpc

  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: woodpecker-server
      labels: *labels
    spec:
      selector:
        matchLabels: *labels
      template:
        metadata:
          labels: *labels
        spec:
          containers:
            - name: woodpecker-server
              image: docker.io/woodpeckerci/woodpecker-server
              imagePullPolicy: Always
              envFrom:
                - configMapRef:
                    name: woodpecker-server
                - secretRef:
                    name: woodpecker-server
              ports:
                - name: http
                  containerPort: 8000
                - name: grpc
                  containerPort: 9000
              readinessProbe:
                httpGet:
                  port: http
                  path: /healthz
              resources:
                requests:
                  cpu: "0.2"
                  memory: "200M"
                limits:
                  memory: "200M"
