apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: memos

labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      app.kubernetes.io/part-of: memos

images:
  - name: ghcr.io/usememos/memos
    newTag: "0.23"

resources:
- manifests/namespace.yml
- manifests/storage.yml
- manifests/deployment.yml
- manifests/service.yml
- manifests/ingress.yml
