---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: base-system
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: basic-cluster configuration from lillinfra
  sourceRepos: 
    - "git@git.lly.sh:lilly/lillinfra.git"
  destinations:
    - name: in-cluster
      server: https://kubernetes.default.svc
      namespace: "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"



---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: apps
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: apps from lillinfra
  sourceRepos:
    - "git@git.lly.sh:lilly/lillinfra.git"
  destinations:
    - name: in-cluster
      server: https://kubernetes.default.svc
      namespace: "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
